import "./globals.css";
import { Poppins } from "next/font/google";
import AuthProvider from "@/app/components/AuthProvider"; // Autenticar
import Header from "./components/Header";
import RegisterLoginButtons from "./components/RegisterLoginButtons";
import Footer from "./components/Footer";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Só Cozinho Verde",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <div className="flex flex-col min-h-screen">
            <Header />
            <RegisterLoginButtons />
            <main className="flex-grow">
              {children}
            
            </main>
            <Footer />
          </div>
        </AuthProvider>
        
      </body>
    </html>
  );
}